# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
