# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 17:46
from __future__ import unicode_literals

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171002_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='f',
            field=models.FileField(upload_to=common.utils.chunked_path, verbose_name='Файл'),
        ),
    ]
