# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171002_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(default='Без названия', max_length=300),
        ),
    ]
