# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171003_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_content',
            field=models.TextField(verbose_name='Файл'),
        ),
    ]
